# -*- coding: utf-8 -*-
"""create_call.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-P4yaLKUPe8WR6KkdR76riOl8rSP4moN
"""

# ============================================================
# 1) INSTALAR gTTS
# ============================================================
!pip install -q gTTS

# ============================================================
# 2) IMPORTS E CONFIG
# ============================================================
from gtts import gTTS
from pathlib import Path
from google.colab import files
import random
import time
import shutil

OUTPUT_DIR = Path("/content/audios_telemarketing_vivo_fibra")
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

# ============================================================
# 3) NOMES VARIÁVEIS
# ============================================================
nomes_operadores = ["Ana Carolina", "Lucas Mendes", "Fernanda Lima", "Rafael Costa", "Juliana Silva"]
nomes_clientes = ["Maria Oliveira", "José Santos", "Ana Paula", "Carlos Roberto", "Luiza Ferreira"]

# ============================================================
# 4) 3 VERSÕES DE DIÁLOGO TELEMARKETING VIVO FIBRA
# ============================================================
dialogos = [
    # VERSÃO 1: Cliente Receptivo (fecha negócio)
    """
OPERADOR: Oi, bom dia! Sou da Vivo Fibra, falo com a Maria Oliveira? Meu nome é Ana Carolina, estou ligando pra te oferecer uma super oferta de economia na internet. (tom animado)

CLIENTE: Bom dia! Sim, sou eu. O que é? (receptivo)

OPERADOR: Perfeito, Maria! Você já tem wifi em casa hoje? Ahn?

CLIENTE: Tenho sim, da Claro, mas tá bem instável.

OPERADOR: Entendi perfeitamente. E quanto você paga aproximadamente na sua internet atual?

CLIENTE: Uns 120 reais por 200 mega, que é lentinho.

OPERADOR: Nossa, Maria, você pode economizar bastante! Olha essa oferta exclusiva pra você: plano de 500 Mega por só 90 reais no cartão, com Wi-Fi 6 de última geração que conecta tudo sem travar, mais 6 meses de Amazon Prime grátis e 1 ano de Perplexity Pro IA. Instalação gratuita com 12 meses de fidelidade online. É pra economizar e ter mais velocidade!

CLIENTE: Hmm, parece bom. Wi-Fi 6 é o novo mesmo?

OPERADOR: Exato! Até 9 gigabits teóricos, baixa latência pra jogos e home office, e app Vivo Smart pra gerenciar tudo. Posso verificar seu CEP rapidinho pra confirmar?

CLIENTE: Meu CEP é 15090-000. Pode verificar.

OPERADOR: Verificando aqui... Perfeito, disponível! Quer ativar hoje e começar a economizar?

CLIENTE: Sim, vamos nessa! Como faz?

OPERADOR: Ótimo! Vou agendar a instalação grátis. Obrigada pela confiança, Maria. Tenha um excelente dia!

CLIENTE: Valeu, Ana. Bom dia!
    """,

    # VERSÃO 2: Cliente Resistente (recusa educada)
    """
OPERADOR: Boa tarde! Vivo Fibra aqui, falo com o José Santos? Eu sou Lucas Mendes, com uma oferta imperdível pra você economizar na internet fibra. (tom confiante)

CLIENTE: Boa tarde. Sim, sou eu. Mas tô sem tempo agora. (apressado)

OPERADOR: Entendo, José, só 1 minutinho. Você tem internet em casa hoje?

CLIENTE: Tenho, Vivo Easy de 300 mega.

OPERADOR: Legal! E o valor mensal é quanto mais ou menos?

CLIENTE: 110 reais, tô satisfeito.

OPERADOR: Perfeito, mas imagina 500 Mega com Wi-Fi 6 por 90 reais, bônus adimplência, Amazon Prime 6 meses, Skeelo Audiobooks e instalação zero? Mais Vivo Total com celular descontado. Economia real pra mesma qualidade superior!

CLIENTE: Não quero fidelidade de 12 meses, prefiro liberdade.

OPERADOR: Entendo, José. A fidelidade é online flexível, cancela pelo app se precisar, mas 99% ficam pelo preço imbatível e Wi-Fi 6 que evita travamentos. Gamer? Tem 700 Mega com ExitLag.

CLIENTE: Não, obrigado. Já tá bom assim.

OPERADOR: Sem problemas, José. Se mudar de ideia, meu contato fica salvo. Bom dia!

CLIENTE: Valeu. Tchau.
    """,

    # VERSÃO 3: Cliente Indeciso (marca retorno)
    """
OPERADOR: Alô, bom dia! Aqui é Fernanda Lima da Vivo Fibra, posso falar com Ana Paula? Tô com uma oferta de economia exclusiva pra sua região em 2026. (tom amigável)

CLIENTE: Bom dia, sim. Fala. (desconfiado)

OPERADOR: Ótimo, Ana! Primeiro, você usa internet fixa aí em casa?

CLIENTE: Uso, TIM de 400 mega, mas reclamo da instabilidade.

OPERADOR: Ahn, clássico isso. Quanto sai mais ou menos na fatura?

CLIENTE: 130 reais, caro pra lentidão.

OPERADOR: Ana, pra você economizar: 700 Mega Gamer por 150 reais, com 1 ponto cabeado, ExitLag, Wi-Fi 6 pra múltiplos devices sem perda, mais Bancah, Vivo Home Assist e 1 ano Perplexity Pro grátis. CEP disponível?

CLIENTE: Parece interessante, mas preciso pensar e falar com o marido.

OPERADOR: Claro, entendo perfeitamente. A oferta é só essa semana pra economia máxima. Posso ligar amanhã à noite pra confirmar?

CLIENTE: Pode sim, às 19h.

OPERADOR: Anotado! Obrigada pela atenção, Ana Paula. Até amanhã!

CLIENTE: Até. Obrigada.
    """
]

# ============================================================
# 5) FUNÇÃO PARA GERAR UMA FALA (MP3, PT-BR)
# ============================================================
def gerar_arquivo_audio(texto: str, file_path: Path):
    tts = gTTS(text=texto, lang="pt-br", slow=False)
    tts.save(str(file_path))

# ============================================================
# 6) FUNÇÃO PARA GERAR UMA LIGAÇÃO TELEMARKETING
# ============================================================
def gerar_ligacao_telemarketing(versao: int):
    operador = random.choice(nomes_operadores)
    cliente = random.choice(nomes_clientes)

    # Substituir nomes no diálogo
    dialogo = dialogos[versao-1].format(operador=operador, cliente=cliente)

    falas = []
    for linha in dialogo.split('\n'):
        linha = linha.strip()
        if linha.startswith('OPERADOR:'):
            texto = linha[9:].strip()
            falas.append(("operador", texto))
        elif linha.startswith('CLIENTE:'):
            texto = linha[8:].strip()
            falas.append(("cliente", texto))

    pasta_ligacao = OUTPUT_DIR / f"telemarketing_v{versao}_{random.randint(100,999)}"
    pasta_ligacao.mkdir(exist_ok=True, parents=True)

    for idx, (falante, texto) in enumerate(falas, start=1):
        file_path = pasta_ligacao / f"{falante}_{idx:02d}.mp3"
        gerar_arquivo_audio(texto, file_path)
        print(f"Versão {versao} - {falante} fala {idx:02d} OK")
        time.sleep(0.3)  # Pausa maior pra evitar rate limit

    print(f"✅ Ligação Telemarketing Versão {versao} concluída.\n")

# ============================================================
# 7) GERAR AS 3 VERSÕES (expanda se quiser mais)
# ============================================================
print("🚀 Iniciando geração de 3 versões de ligações telemarketing Vivo Fibra...")
for i in range(1, 4):
    gerar_ligacao_telemarketing(i)
    time.sleep(1)

print("🎯 Todas as 3 versões geradas em:", OUTPUT_DIR)

# ============================================================
# 8) ZIPAR E BAIXAR
# ============================================================
zip_path = "/content/audios_telemarketing_vivo_fibra_3_versoes.zip"
shutil.make_archive(zip_path.replace(".zip", ""), "zip", OUTPUT_DIR)
print("📦 ZIP criado em:", zip_path)
files.download(zip_path)
print("⬇️ Download iniciado. Descompacte e ouça as variações!")